# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - to-do-app-10

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_185ad311abde491a9fa0f5edae22ae3f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_343ae3887d2447688cad2241b8db7c23 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_185ad311abde491a9fa0f5edae22ae3f }}/appsvc/wordpress-alpine-php:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'to-do-app-10'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_bf4a33ea0f894f8c9efadc033894549c }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_185ad311abde491a9fa0f5edae22ae3f }}/appsvc/wordpress-alpine-php:${{ github.sha }}'